config/routes.rb
Brs::Application.routes.draw do
  root to:  'static_pages#home'
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get "users/new"
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signin',  to: 'sessions#new',         via: 'get'

  resources :books do
    resources :rates, only: [:create, :destroy, :update, :edit]
    resources :favourites, only: [:create]
    resources :buys, only: [:create, :destroy]
    resources :reviews do
    resources :comments
    end
  end

  resources :users do
    resources :favourites, only: [:index]
    resources :buys, only: [:index]
    member do
      get :following, :followers
    end
  end
  resources :readings, only: [:index, :create]
  resources :reads, only: [:create]
  resources :searchs
  resources :likes, only: [:create, :destroy]

  namespace :admin do
    root to: 'books#index'
    resources :books
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    match 'signout', to: 'sessions#destroy',     via: 'delete'
    match 'signin',  to: 'sessions#new',         via: 'get'
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :reviews
	has_many :buys
	has_many :favourites
	has_many :reads
	has_many :readings
	has_many :rates

  scope :search_book_by_title_cat, lambda { |title, category_id| {conditions: "title LIKE \"%#{title}%\" AND category_id = #{category_id}"} }



end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
	include BooksHelper
  before_action :signed_in_admin

	def index
			@books = Book.paginate page: params[:page], per_page: 2
	end

	def show

	end

	def new
		@book = Book.new
		@categories = Category.all
	end

	def create
		@book= Book.new book_params
	    if @book.save
	      flash[:success] = "Create new book success!"
	      redirect_to admin_books_path
	    else
	      render 'new'
	    end
	end

	def edit
		@book = Book.find params[:id]
		@categories = Category.all
	end

	def update
		@book = Book.find params[:id] 
    if @book.update_attributes! book_params
      flash[:success] = "Book updated"
      redirect_to admin_books_path
    else
      render 'edit'
    end
	end

	def destroy
		@book = Book.find params[:id]
		unless !@book.nil? && book_using?(@book)
		  @book.destroy
      flash[:success] = "Book deleted."
      redirect_to admin_books_path
    else
    	flash[:error] = "Book using. You can't remove."
      redirect_to admin_books_path
    end
	end

	private

	    def book_params
	      params.require(:book).permit(:title, :category_id, :price, 
	      														 :num_page, :author, :publish_date)
	    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.paginate page: params[:page], per_page: 8
  end

  def show
    @book = Book.find params[:id]
    @reviews = @book.reviews.paginate page: params[:page], per_page: 8
    @rate = current_user.rates.rate_number(@book.id).first unless current_user.nil?
    @buy = current_user.buys.bought(@book.id).first unless current_user.nil?
  end

end

app/helpers/books_helper.rb
module BooksHelper

	def book_using? book
		book.buys.any? || book.favourites.any? ||
		book.reads.any? || book.readings.any? ||
		book.rates.any? || book.reviews.any?
	end

end

app/views/admin/books/_book.html.erb
<tr>
	<td><%= book.id %></td>
	<td><%= link_to book.title, admin_book_path(book) %>
	</td>
	<td><%= book.rating%></td>
	<td><%= book.publish_date%></td>
	<td><%= book.num_page%></td>
	<td><%= book.price%>$</td>
	<td><%= book.category.name %></td>
	<td><%= "so favourites"%></td>
	<td><%= link_to "Edit", edit_admin_book_path(book),
	                              class: "btn btn-small btn-primary" %></td>
	<td><%= link_to "Delete", admin_book_path(book), method: :delete,
                                  data: { confirm: "You sure?" },
                                  class: "btn btn-small btn-primary"%>
</tr>

app/views/admin/books/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
      
<div class="field">
	<%= f.label :title %>
  <%= f.text_field :title, placeholder: "Compose new title..." %>
</div>
<div class="field">
	<%= f.label "Category" %>
  <%= f.collection_select(:category_id, categories, :id, :name) %>
</div>
<div class="field">
	<%= f.label "Number page" %>
  <%= f.number_field :num_page %>
</div>
<div class="field">
	<%= f.label :price %>
  <%= f.number_field :price %>
</div>
<div class="field">
	<%= f.label :author %>
  <%= f.text_field :author %>
</div>
<div class="field">
	<%= f.label :publish_date %>
  <%= f.date_field :publish_date %>
</div>

app/views/admin/books/edit.html.erb
<% provide(:title, 'Edit book') %>
<h1>Update book</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for [:admin, @book] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
			<%= render 'fields', f: f, categories: @categories%>

      <%= f.submit "Update book", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide(:title, "Show all books") %>
<h2>Show all books</h2>
<%= link_to "Create new book", new_admin_book_path,
	                              class: "btn btn-small btn-primary" %>
<table class="table">
	<thear>
		<tr>
			<th>STT</th>
			<th>Title books</th>
			<th>Rating</th>
			<th>Publish date</th>
			<th>Num page</th>
			<th>Price</th>
			<th>Category</th>
			<th>Favourites</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
  </thear>
	<tbody>
		<% if @books.any? %>
		<%= render @books %>
		<% end %>
	</tbody>
	<tfoot>
    <%= will_paginate %>
	</tfoot>
</table>

app/views/admin/books/new.html.erb
<% provide(:title, 'Create a new book') %>
<h1>Create a new book</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for [:admin, @book] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
			<%= render 'fields', f: f, categories: @categories%>

      <%= f.submit "Create book", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>