config/routes.rb
Brs::Application.routes.draw do
  root to:  'static_pages#home'
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get "users/new"
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signin',  to: 'sessions#new',         via: 'get'

  resources :books do
    resources :rates, only: [:create, :destroy, :update, :edit]
    resources :favourites, only: [:create]
    resources :buys, only: [:create, :destroy]
    resources :reviews do
    resources :comments
    end
  end

  resources :users do
    resources :favourites, only: [:index]
    resources :buys, only: [:index]
    member do
      get :following, :followers
    end
  end
  resources :readings, only: [:index, :create]
  resources :reads, only: [:create]
  resources :searchs
  resources :likes, only: [:create, :destroy]

  namespace :admin do
    root to: 'books#index'
    resources :books
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    match 'signout', to: 'sessions#destroy',     via: 'delete'
    match 'signin',  to: 'sessions#new',         via: 'get'
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
    @book = Book.new
  end

  def new
    @books = Book.search_book_by_title_cat(params[:title],
     params[:category_id]).paginate page: params[:page], per_page: 8
  end

end

app/views/searchs/index.html.erb
<% provide(:title, "Search book") %>
<h1>Search Book</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_tag new_search_path, method: "get" do %>

      <%= label_tag :title %>
      <%= text_field_tag :title, params[:title] %>

      <%= label_tag "Category" %>
      <% categories_array = Category.all.map { |category| [category.name, category.id] } %>
      <%= select_tag "category_id", options_for_select(categories_array) %>

      <%= submit_tag "Search", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/searchs/new.html.erb
<% provide(:title, 'Result Books') %>
<h1>Result Books</h1>

<% if @books.any? %>
<table cellpadding="2" cellspacing="0" width="100%">
  <tr>
		<td class="listbox-header" align="center">
			Title
		</td>
		<td class="listbox-header" align="center">Author</td>
		<td class="listbox-header" align="center">Publish at</td>
		<td class="listbox-header" align="center">Price</td>
		<td class="listbox-header" align="center">Category</td>
	</tr>

	<%= render @books %>
	<%= will_paginate @books %>
</table>
<% else %>
  <h1>There aren't any book that you looking for</h1>
<% end %>